name: KESS MEDIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47503
title: Creations by Alexander Kesselaar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#5e5c5c'
    - '#a7a4a4'
    - '#292828'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5240658558905125
purpose: []
